package transport

const (
	HandlerIDControllerRegisterL0Table = iota + 10
	HandlerIDControllerApplyChanges
	HandlerIDControllerQueryTablesInRange
	HandlerIDControllerRegisterTableListener
	HandlerIDControllerPrepush
	HandlerIDControllerGetOffsetInfo
	HandlerIDControllerPollForJob
	HandlerIDControllerGetAllTopicInfos
	HandlerIDControllerGetTopicInfo
	HandlerIDControllerGetTopicInfoByID
	HandlerIDControllerCreateTopic
	HandlerIDControllerDeleteTopic
	HandlerIDControllerGetGroupCoordinatorInfo
	HandlerIDControllerGenerateSequence
	HandlerIDControllerPutUserCredentials
	HandlerIDControllerDeleteUserCredentials
	HandlerIDControllerAuthorise
	HandlerIDControllerCreateAcls
	HandlerIDControllerListAcls
	HandlerIDControllerDeleteAcls
	HandlerIDMetaLocalCacheTopicAdded
	HandlerIDMetaLocalCacheTopicDeleted
	HandlerIDFetchCacheGetTableBytes
	HandlerIDFetcherTableRegisteredNotification
	HandlerIDTablePusherDirectWrite
	HandlerIDTablePusherDirectProduce
)
