package transport

const (
	HandlerIDControllerRegisterL0Table = iota + 10
	HandlerIDControllerApplyChanges
	HandlerIDControllerQueryTablesInRange
	HandlerIDControllerRegisterTableListener
	HandlerIDControllerGetOffsets
	HandlerIDControllerPollForJob
	HandlerIDControllerGetTopicInfo
	HandlerIDControllerCreateTopic
	HandlerIDControllerDeleteTopic
	HandlerIDMetaLocalCacheTopicAdded
	HandlerIDMetaLocalCacheTopicDeleted
	HandlerIDFetcherOffsetNotification
)
