package iteration

import (
	"github.com/spirit-labs/tektite/common"
)

// # Iterator interface.
//
// Next() method generates the next element in the iterator.
//
// Current() method returns the latest element generated by the iterator (i.e. the latest returned by Next()).
// In case Current() is called before the first call to Next(), it should return KV's zero value.
type Iterator interface {
	Next() (bool, common.KV, error)
	Current() common.KV
	Close()
}
